using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class CreatePartyWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _partyManager = default!;

    public CreatePartyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CreateButton.OnPressed += _ =>
        {
            var state = SettingsPanel.GetSettingsState();
            _partyManager.SendCreatePartyRequest(state);
            Close();
        };
        CancelButton.OnPressed += _ => Close();

        this.OnOpen += SettingsPanel.Update;
    }
}
