using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class InvitedInPartyWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _partyManager = default!;

    private PartyInvite _invite;

    public InvitedInPartyWindow(PartyInvite invite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _invite = invite;

        SenderLabel.Text = Loc.GetString("ui-InvitedInPartyWindow-SenderLabel", ("sender", _invite.SenderName));
        AcceptButton.OnPressed += _ =>
        {
            _partyManager.AcceptInvite(_invite);
        };

        DenyButton.OnPressed += _ =>
        {
            _partyManager.DenyInvite(_invite);
        };
    }

    public override void Close()
    {
        base.Close();
        _partyManager.DenyInvite(_invite);
    }
}
