using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Content.Shared.SS220.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;
using System.Threading.Tasks;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class InviteInPartyWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _partyManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public InviteInPartyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InvitesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(32, 32, 40) };
        InputLine.PlaceHolder = Loc.GetString("ui-InviteInPartyWindow-Placeholder");
        InviteButton.OnPressed += _ => SendInvite();

        _partyManager.OnSendedInviteAdded += _ => Populate();
        _partyManager.OnSendedInviteRemoved += _ => Populate();
        _partyManager.OnSendedInviteUpdated += _ => Populate();

        Populate();
    }

    public void Populate()
    {
        var invites = _partyManager.SendedInvites;

        var limit = _cfg.GetCVar(CCVars220.PartyInvitesLimit);
        var invitesCountInfo = Loc.GetString("ui-InviteInPartyWindow-sended-invites-count", ("count", invites.Count), ("limit", limit));
        InvitesCountLabel.Text = invitesCountInfo;

        InvitesContainer.RemoveAllChildren();
        foreach (var (id, invite) in invites)
        {
            var control = new SendedInvitePanel(invite);
            control.Margin = new Thickness(5);
            control.CancelButton.OnPressed += _ =>
            {
                _partyManager.DeleteInviteRequest(id);
            };
            InvitesContainer.AddChild(control);
        }
    }

    public async void SendInvite()
    {
        var text = InputLine.Text;
        if (string.IsNullOrEmpty(text))
            return;

        var responce = await _partyManager.InviteUserRequestAsync(text);
        if (responce.Timeout)
        {
            AddFailReason("Истекло время ожидания ответа");
            return;
        }

        if (!responce.Success)
        {
            AddFailReason(responce.Text);
            return;
        }
    }

    private void AddFailReason(string reason, TimeSpan? showTime = null)
    {
        showTime ??= TimeSpan.FromSeconds(10);

        var msg = new FormattedMessage();
        msg.PushColor(Color.Red);
        msg.AddText(reason);
        msg.Pop();

        FailReasonLabel.SetMessage(msg);

        RemoveFailReason((int)showTime.Value.TotalMilliseconds);
    }

    private async void RemoveFailReason(int delay)
    {
        await Task.Delay(delay);

        FailReasonLabel.Text = null;
    }
}
