using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class InviteInPartyWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _partyManager = default!;

    public InviteInPartyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InvitesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(32, 32, 40) };
        InputLine.PlaceHolder = "Введите ckey игрока, которого хотите пригласить";
        InviteButton.OnPressed += _ => SendInvite();

        _partyManager.OnSendedInviteAdded += _ => Populate();
        _partyManager.OnSendedInviteRemoved += _ => Populate();
        _partyManager.OnSendedInviteUpdated += _ => Populate();
        Populate();
    }

    public void Populate()
    {
        var invites = _partyManager.SendedInvites;

        var invitesCountInfo = $"Отправлено приглашений: {invites.Count}/5";
        InvitesCountLabel.Text = invitesCountInfo;

        InvitesContainer.RemoveAllChildren();
        foreach (var (id, invite) in invites)
        {
            var control = new SendedInvitePanel(invite);
            control.Margin = new Thickness(5);
            control.CancelButton.OnPressed += _ =>
            {
                _partyManager.DeleteInvite(id);
            };
            InvitesContainer.AddChild(control);
        }
    }

    public void SendInvite()
    {
        var text = InputLine.Text;
        if (string.IsNullOrEmpty(text))
            return;

        _partyManager.SendInvite(text);
    }
}
