// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Content.Shared.SS220.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;
using System.Threading.Tasks;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class LocalPartyInvitesWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public LocalPartyInvitesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InvitesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(32, 32, 40) };
        InputLine.PlaceHolder = Loc.GetString("ui-local-party-invites-window-inputline-placeholder");
        InviteButton.OnPressed += _ => SendInvite();

        if (_party.LocalParty is { } party)
        {
            party.InviteAdded += _ => Refresh();
            party.InviteRemoved += _ => Refresh();
        }

        _party.LocalPartyChanged += party =>
        {
            if (party is null)
                return;

            party.InviteAdded += _ => Refresh();
            party.InviteRemoved += _ => Refresh();
        };

        Refresh();
    }

    public void Refresh()
    {
        InvitesContainer.DisposeAllChildren();
        if (_party.LocalParty is not { } party)
            return;

        var invites = party.Invites;

        var limit = _cfg.GetCVar(CCVars220.PartyInvitesLimit);
        var invitesCountInfo = Loc.GetString("ui-local-party-invites-window-sended-invites-count", ("count", invites.Count), ("limit", limit));
        InvitesCountLabel.Text = invitesCountInfo;

        foreach (var invite in invites)
        {
            var control = new LocalPartyInvitePanel(invite)
            {
                Margin = new Thickness(5)
            };
            InvitesContainer.AddChild(control);
        }
    }

    public async void SendInvite()
    {
        var text = InputLine.Text;
        if (string.IsNullOrEmpty(text))
            return;

        var responce = await _party.InviteUserRequestAsync(text);
        if (responce.Timeout)
        {
            AddFailReason(Loc.GetString("ui-local-party-invites-window-send-failreason-timeout"));
            return;
        }

        if (!responce.Success)
        {
            AddFailReason(responce.Text);
            return;
        }
    }

    private void AddFailReason(string reason, TimeSpan? showTime = null)
    {
        showTime ??= TimeSpan.FromSeconds(10);

        var msg = new FormattedMessage();
        msg.PushColor(Color.Red);
        msg.AddText(reason);
        msg.Pop();

        FailReasonLabel.SetMessage(msg);

        RemoveFailReason((int)showTime.Value.TotalMilliseconds);
    }

    private async void RemoveFailReason(int delay)
    {
        await Task.Delay(delay);

        FailReasonLabel.Text = null;
    }
}
