using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class PartySettingsWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _partyManager = default!;

    public PartySettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AcceptButton.OnPressed += _ =>
        {
            var settings = SettingsPanel.GetSettingsState();
            _partyManager.SetSettingsRequest(settings);
            Close();
        };

        OnOpen += SettingsPanel.Update;
    }
}
