using Content.Client.SS220.SpaceWars.Party.UI.Tabs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class PartyWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _party = default!;

    public PartyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Refresh();

        _party.CurrentPartyUpdated += Refresh;

        Tabs.SetTabTitle(0, Loc.GetString("ui-party-main-tab-name"));
        Tabs.SetTabTitle(1, Loc.GetString("ui-received-invites-tab-name"));
    }

    protected override void Opened()
    {
        Refresh();
    }

    public void Refresh()
    {
        PartyMainTab.Refresh();
        ReceivedInvitesTab.Refresh();
    }
}
