
using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Content.Shared.SS220.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;
using System.Linq;
using System.Threading.Tasks;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class SendedPartyInvitesWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public SendedPartyInvitesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InvitesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(32, 32, 40) };
        InputLine.PlaceHolder = Loc.GetString("ui-local-party-invites-window-inputline-placeholder");
        InviteButton.OnPressed += _ => SendInvite();

        _party.InviteAdded += invite =>
        {
            if (invite.Kind is not PartyInviteKind.Sended)
                return;

            Refresh();
        };
        _party.InviteRemoved += invite =>
        {
            if (invite.Kind is not PartyInviteKind.Sended)
                return;

            Refresh();
        };

        Refresh();
    }

    public void Refresh()
    {
        var invites = _party.SendedInvites;

        var limit = _cfg.GetCVar(CCVars220.PartyInvitesLimit);
        var invitesCountInfo = Loc.GetString("ui-local-party-invites-window-sended-invites-count", ("count", invites.Count()), ("limit", limit));
        InvitesCountLabel.Text = invitesCountInfo;

        InvitesContainer.DisposeAllChildren();
        foreach (var invite in invites)
        {
            var control = new SendedPartyInvitePanel(invite)
            {
                Margin = new Thickness(5)
            };
            InvitesContainer.AddChild(control);
        }
    }

    public async void SendInvite()
    {
        var text = InputLine.Text;
        if (string.IsNullOrEmpty(text))
            return;

        var responce = await _party.InviteUserRequestAsync(text);
        if (responce.Timeout)
        {
            AddFailReason(Loc.GetString("ui-local-party-invites-window-send-failreason-timeout"));
            return;
        }

        if (!responce.Success)
        {
            AddFailReason(responce.Text);
            return;
        }
    }

    private void AddFailReason(string reason, TimeSpan? showTime = null)
    {
        showTime ??= TimeSpan.FromSeconds(10);

        var msg = new FormattedMessage();
        msg.PushColor(Color.Red);
        msg.AddText(reason);
        msg.Pop();

        FailReasonLabel.SetMessage(msg);

        RemoveFailReason((int)showTime.Value.TotalMilliseconds);
    }

    private async void RemoveFailReason(int delay)
    {
        await Task.Delay(delay);

        FailReasonLabel.Text = null;
    }
}
