using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class IncomingInvitesTab : Control
{
    [Dependency] private readonly IPartyManager _partyManager = default!;

    public IncomingInvitesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InvitesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(32, 32, 40) };
        _partyManager.OnIncomingInviteAdded += _ => Populate();
        _partyManager.OnIncomingInviteRemoved += _ => Populate();
    }

    public void Populate()
    {
        InvitesContainer.RemoveAllChildren();
        var invites = _partyManager.IncomingInvites;
        if (invites.Count <= 0)
            return;

        foreach (var (id, invite) in invites)
        {
            var control = new IncomingInvite(invite);
            control.Margin = new Thickness(5);
            control.AcceptButton.OnPressed += _ =>
            {
                _partyManager.AcceptInvite(id);
            };

            control.DenyButton.OnPressed += _ =>
            {
                _partyManager.DenyInvite(id);
            };
            InvitesContainer.AddChild(control);
        }
    }


}
