// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Content.Client.SS220.UserInterface.Utility;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;

namespace Content.Client.SS220.SpaceWars.Party.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class PartyMainTab : Control
{
    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IUserInterfaceManager _userInterface = default!;

    private readonly Dictionary<NetUserId, PartyMemberPanel> _memberPanels = [];

    private readonly CreatePartyWindow _createPartyWindow = new();
    private readonly LocalPartyInvitesWindow _localPartyInvitesWindow = new();
    private readonly PartySettingsWindow _partySettingsWindow = new();

    private static readonly Color NotMemberOverlayColor = new(18, 18, 20, 230);

    private static readonly Thickness MemberPanelThickness = new(5, 5, 5, 0);
    private static readonly Thickness ChatMessageLabelThickness = new(5, 2, 5, 0);

    private static readonly ConfirmableButtonState ConfirmableButtonFirstClickState =
        new(Loc.GetString("ui-party-main-tab-confirmable-button-are-you-sure"), StyleNano.ButtonColorCautionDefault);

    private Vector2 MousePosition => _userInterface.MousePositionScaled.Position;

    public PartyMainTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MembersPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultInnerBackgroundColor };
        ChatPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultInnerBackgroundColor };

        NotMemberOverlay.PanelOverride = new StyleBoxFlat { BackgroundColor = NotMemberOverlayColor };

        _party.ChatMessageReceived += AddChatMessage;

        MembersContainer.OnResized += RefreshMembers;

        LeavePartyButton.SetClickState(0, new ConfirmableButtonState(Loc.GetString("ui-party-main-tab-leave-party-button"), null));
        LeavePartyButton.SetClickState(1, ConfirmableButtonFirstClickState);

        DisbandPartyButton.SetClickState(0, new ConfirmableButtonState(Loc.GetString("ui-party-main-tab-disband-party-button"), null));
        DisbandPartyButton.SetClickState(1, ConfirmableButtonFirstClickState);

        CreatePartyButton.OnPressed += _ => _createPartyWindow.Open(MousePosition);
        LeavePartyButton.OnConfirmed += _party.LeavePartyRequest;
        DisbandPartyButton.OnConfirmed += _party.DisbandPartyRequest;
        PartyInvitesButton.OnPressed += _ => _localPartyInvitesWindow.Open(MousePosition);
        PartySettingsButton.OnPressed += _ => _partySettingsWindow.Open(MousePosition);

        Refresh();
    }

    public void Refresh()
    {
        RefreshMembers();
        RefreshChat();
        RefreshButtons();
        RefreshNotMemberOverlay();

        if (_party.LocalParty is null)
        {
            _localPartyInvitesWindow.Close();
            _partySettingsWindow.Close();
        }
        else
            _createPartyWindow.Close();
    }

    private void RefreshMembers()
    {
        var toRemove = _memberPanels.Keys.ToList();
        MembersContainer.RemoveAllChildren();

        if (_party.LocalParty is { } party)
        {
            var members = party.Members.OrderByDescending(m => m.Role).ThenBy(m => m.Username);
            foreach (var member in members)
            {
                if (_memberPanels.TryGetValue(member.UserId, out var memberPanel))
                {
                    memberPanel.Refresh();
                    toRemove.Remove(member.UserId);
                }
                else
                {
                    memberPanel = new(member)
                    {
                        Margin = MemberPanelThickness
                    };

                    _memberPanels.Add(member.UserId, memberPanel);
                }

                MembersContainer.AddChild(memberPanel);
            }

            var membersLimit = party.Settings.MembersLimit;
            MaxMembersLabel.SetMessage(Loc.GetString("ui-party-main-tab-members-limit-label", ("count", members.Count()), ("limit", membersLimit)));
        }
        else
        {
            MaxMembersLabel.SetMessage(string.Empty);
        }

        foreach (var key in toRemove)
            _memberPanels.Remove(key);
    }

    #region Chat
    private void RefreshChat()
    {
        if (_party.LocalParty is null)
            ChatBox.RemoveAllChildren();
    }

    public void AddChatMessage(string message)
    {
        var label = new RichTextLabel()
        {
            Margin = ChatMessageLabelThickness
        };

        var msg = new FormattedMessage();
        msg.AddMarkupPermissive(message);

        label.SetMessage(msg);
        ChatBox.AddChild(label);
    }
    #endregion

    private void RefreshButtons()
    {
        var inParty = _party.LocalParty is not null;
        CreatePartyButton.Visible = !inParty;
        LeavePartyButton.Visible = inParty;

        var isHost = _party.IsLocalPartyHost;
        DisbandPartyButton.Visible = isHost;
        PartyInvitesButton.Visible = isHost;
        PartySettingsButton.Visible = isHost;

        LeavePartyButton.SetOnlyStyleClass(ContainerButton.StyleClassButton);
        if (isHost)
            LeavePartyButton.AddStyleClass(StyleBase.ButtonOpenRight);
    }

    private void RefreshNotMemberOverlay()
    {
        var visible = _party.LocalParty is null;
        NotMemberOverlay.Visible = visible;
        NotMemberLabel.Visible = visible;
    }
}
