// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using System.Numerics;
using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Content.Client.SS220.UserInterface.Utility;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ReceivedPartyInvitesTab : Control
{
    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly QuickConfirmationWindow _confirmationWindow = new();
    private readonly Dictionary<PartyInvite, ReceivedPartyInvitePanel> _invitePanels = [];

    private static readonly Vector2 ConfirmationWindowSize = new(400, 80);

    public ReceivedPartyInvitesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InvitesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultInnerBackgroundColor };

        _party.ReceivedInviteAdded += AddInvite;
        _party.ReceivedInviteRemoved += RemoveInvite;

        ReceiveInvitesCheckbox.OnToggled += button =>
        {
            _party.SetReceiveInvitesStatus(button.Pressed);
        };

        _confirmationWindow.SetSize = ConfirmationWindowSize;

        Refresh();
    }

    public void Refresh()
    {
        InvitesContainer.RemoveAllChildren();
        _invitePanels.Clear();

        foreach (var invite in _party.ReceivedInvites)
            AddInvite(invite);
    }

    private void AddInvite(PartyInvite invite)
    {
        if (invite.Target != _player.LocalUser)
            return;

        if (_invitePanels.ContainsKey(invite))
            return;

        var panel = new ReceivedPartyInvitePanel(invite)
        {
            Margin = new Thickness(5)
        };

        InvitesContainer.AddChild(panel);
        _invitePanels.Add(invite, panel);

        UpdateInvitesCountLabel();
    }

    private void RemoveInvite(PartyInvite invite)
    {
        if (!_invitePanels.TryGetValue(invite, out var panel))
            return;

        InvitesContainer.RemoveChild(panel);
        _invitePanels.Remove(invite);

        UpdateInvitesCountLabel();
    }

    private void UpdateInvitesCountLabel()
    {
        var count = _invitePanels.Count;
        InvitesCountLabel.Text = Loc.GetString("ui-received-invites-tab-invites-count-label", ("count", count));
    }
}
