using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class Signature : Container
{
    public Signature()
    {
        RobustXamlLoader.Load(this);
    }


}
