using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class IncomingInvite : PanelContainer
{
    private PartyInvite _invite;

    public IncomingInvite(PartyInvite invite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _invite = invite;
        PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(60, 60, 60) };
        SenderLabel.Text = Loc.GetString("ui-InvitedInPartyWindow-SenderLabel", ("sender", _invite.Sender.Name));
    }
}
