using Content.Client.Message;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class LocalPartyInvitePanel : PanelContainer
{
    [Dependency] private readonly IPartyManager _party = default!;

    public readonly PartyInvite Invite;

    public LocalPartyInvitePanel(PartyInvite invite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DebugTools.Assert(_party.InternalInvites.Contains(invite));
        DebugTools.AssertEqual(_party.LocalParty?.Id, invite.PartyId);
        Invite = invite;

        _party.InviteUpdated += args =>
        {
            if (args != Invite)
                return;

            Refresh();
        };

        CancelButton.OnPressed += _ =>
        {
            _party.DeleteInviteRequest(Invite.Id);
        };

        PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(60, 60, 60) };
        Refresh();
    }

    public void Refresh()
    {
        ReceiverLabel.SetMarkup(Loc.GetString("ui-local-party-invite-panel-receiver-label", ("receiver", Invite.ReceiverName)));

        var status = SharedPartyInvite.GetPartyInviteStatusName(Invite.Status);
        StatusLabel.SetMarkup(Loc.GetString("ui-local-party-invite-panel-status-label", ("status", status)));
    }
}
