using Content.Shared.SS220.CCVars;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using System.Diagnostics.CodeAnalysis;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class PartySettingsPanel : PanelContainer
{
    [Dependency] private readonly IPartyManager _partyManager = default!;
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private Dictionary<string, Control> _settings = new();

    public PartySettingsPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Update();
    }

    public void Update()
    {
        SettingsBox.RemoveAllChildren();

        AddLineEditOption(nameof(PartySettings.MaxMembers),
            (_partyManager.CurrentParty?.Settings.MaxMembers ?? _cfg.GetCVar(CCVars220.PartyMembersLimit)).ToString());
    }

    public PartySettingsState GetSettingsState()
    {
        var state = new PartySettingsState();
        if (TryGetSettingValue<string>(nameof(PartySettings.MaxMembers), out var value) &&
            uint.TryParse(value, out var maxMembers))
            state.MaxMembers = maxMembers;

        return state;
    }

    private void AddLineEditOption(string name, string defaultText)
    {
        var box = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        var label = new RichTextLabel()
        {
            SetWidth = 300
        };
        _localizationManager.TryGetString($"ui-PartySettings-LineEdit-{name}", out var labelText);
        labelText ??= name;
        label.SetMessage(labelText);
        box.AddChild(label);

        var edit = new LineEdit
        {
            Text = defaultText,
            HorizontalExpand = true,
            Margin = new Thickness(10, 0, 0, 0)
        };
        box.AddChild(edit);

        SettingsBox.AddChild(box);
        _settings[name] = edit;
    }

    private bool TryGetSettingValue<T>(string name, [NotNullWhen(true)] out T? value)
    {
        value = default(T);
        if (!_settings.TryGetValue(name, out var control))
            return false;

        object? result = null;
        switch (control)
        {
            case LineEdit lineEdit:
                result = lineEdit.Text;
                break;
            default:
                break;
        }

        if (result is not T)
            return false;

        value = (T)result;
        return true;
    }
}
