// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Numerics;
using static Robust.Client.Input.Mouse;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class PartyMemberPanel : PanelContainer
{
    [Dependency] private readonly IResourceCache _cache = default!;
    [Dependency] private readonly IPartyManager _party = default!;

    public readonly PartyMember Member;

    private const string FontResourcePath = "/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf";
    private const int FontSize = 11;

    private static readonly Vector2 ConnectionStatusIconScale = new(0.6f, 0.6f);
    private const string ConnectionStatusIconTexturePath = "/Textures/SS220/Interface/Nano/circle.svg.png";
    private static readonly Color ConnectionStatusIconConnectedColor = Color.Green;
    private static readonly Color ConnectionStatusIconDisconnectedColor = Color.Red;

    private static readonly Dictionary<PartyMemberRole, Color> RolesColor = new()
    {
        {PartyMemberRole.Member, new Color(52, 101, 131)},
        {PartyMemberRole.Host, new Color(146, 122, 25)}
    };

    public PartyMemberPanel(PartyMember member)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Member = member;

        PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultBackgroundColor };
        var textFont = new VectorFont(_cache.GetResource<FontResource>(FontResourcePath), FontSize);

        UsernameLabel.FontOverride = textFont;
        PartyRoleLabel.FontOverride = textFont;
        ConnectionStatusLabel.FontOverride = textFont;

        ConnectionStatusIcon.TexturePath = ConnectionStatusIconTexturePath;
        ConnectionStatusIcon.TextureScale = ConnectionStatusIconScale;

        KickButton.OnPressed += _ => _party.KickFromPartyRequest(member.UserId);

        var kickBurronTooltip = new Tooltip();
        kickBurronTooltip.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("ui-party-main-tab-kick-button-tooltip")));
        KickButton.TooltipSupplier = _ => kickBurronTooltip;

        Refresh();
    }

    public void Refresh()
    {
        UsernameLabel.Text = Member.Username;
        PartyRoleLabel.Text = SharedPartyManager.GetPartyMemberRoleName(Member.Role);

        var roleBackground = GetRoleColor(Member.Role);
        if (roleBackground != null)
            PartyRolePanel.PanelOverride = new StyleBoxFlat() { BackgroundColor = roleBackground.Value };

        ConnectionStatusIcon.ModulateSelfOverride = Member.Connected ? ConnectionStatusIconConnectedColor : ConnectionStatusIconDisconnectedColor;
        ConnectionStatusLabel.Text = Member.Connected
            ? Loc.GetString("ui-party-member-panel-member-connected")
            : Loc.GetString("ui-party-member-panel-member-disconnected");

        KickButton.Visible = _party.IsLocalPartyHost && Member.Role is not PartyMemberRole.Host;
    }

    private static Color? GetRoleColor(PartyMemberRole role)
    {
        RolesColor.TryGetValue(role, out var color);
        return color;
    }
}
