using Content.Shared.SS220.CCVars;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class PartySettingsPanel : PanelContainer
{
    public event Action<PartySettingsState>? OnSettingChanged;

    [Dependency] private readonly IPartyManager _partyManager = default!;
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public PartySettingsPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Refresh();
    }

    public void Refresh()
    {
        MembersLimitLineEdit.SetText((_partyManager.LocalParty?.Settings.MembersLimit ?? _cfg.GetCVar(CCVars220.PartyMembersLimit)).ToString());
    }

    public PartySettingsState GetSettingsState()
    {
        var state = new PartySettingsState();
        if (int.TryParse(MembersLimitLineEdit.Text, out var membersLimit))
            state.MembersLimit = membersLimit;

        return state;
    }
}
