using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class PartyUserInfoPanel : PanelContainer
{
    [Dependency] private readonly IResourceCache _cache = default!;

    private readonly Font _textFont;

    public PartyUserInfoPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(60, 60, 60) };
        _textFont = new VectorFont(_cache.GetResource<FontResource>("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf"), 11);

        UserNameLabel.FontOverride = _textFont;
        PartyRoleLabel.FontOverride = _textFont;
        ConnectionStatusLabel.FontOverride = _textFont;
    }

    public PartyUserInfoPanel(string? username, PartyRole? role, bool conected) : this()
    {
        Populate(username, role, conected);
    }

    public PartyUserInfoPanel(PartyUserInfo userInfo) : this(userInfo.Name, userInfo.Role, userInfo.Connected) { }

    public void Populate(PartyUserInfo userInfo)
    {
        Populate(userInfo.Name, userInfo.Role, userInfo.Connected);
    }

    public void Populate(string? username, PartyRole? role, bool conected)
    {
        UserNameLabel.Text = username;
        PartyRoleLabel.Text = role == null ? null : GetUserRoleName(role.Value);
        ConnectionStatusLabel.Text = conected ? Loc.GetString("ui-PartyUserInfo-Connected") : Loc.GetString("ui-PartyUserInfo-Disconnected");
    }

    private string GetUserRoleName(PartyRole role)
    {
        return role switch
        {
            PartyRole.Member => Loc.GetString("partyRole-Member"),
            PartyRole.Leader => Loc.GetString("partyRole-Leader"),
            _ => Loc.GetString("partyRole-Unknown")
        };
    }
}
