using Content.Client.Message;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class SendedInvitePanel : PanelContainer
{
    private SendedPartyInvite _invite;

    public SendedInvitePanel(SendedPartyInvite invite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(60, 60, 60) };
        _invite = invite;
        Populate();
    }

    public void Populate(SendedPartyInvite invite)
    {
        _invite = invite;
        Populate();
    }

    public void Populate()
    {
        TargetLabel.SetMarkup($"Игрок: {_invite.TargetName}");

        var status = Loc.GetString($"partyinvite-status-{_invite.Status}");
        StatusLabel.SetMarkup($"Статус: {status}");
    }
}
