using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class SendedInvitePanel : PanelContainer
{
    private SendedPartyInvite _invite;

    public SendedInvitePanel(SendedPartyInvite invite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(60, 60, 60) };
        _invite = invite;
        Populate();
    }

    public void Populate(SendedPartyInvite invite)
    {
        _invite = invite;
        Populate();
    }

    public void Populate()
    {
        TargetLabel.Text = $"Игрок: {_invite.TargetName}";
        StatusLabel.Text = $"Статус: {_invite.Status}";
    }
}
