using Content.Client.Message;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class SendedPartyInvitePanel : PanelContainer
{
    [Dependency] private readonly IPartyManager _party = default!;

    public readonly IPartyInvite Invite;

    public SendedPartyInvitePanel(IPartyInvite invite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DebugTools.Assert(invite.Kind is PartyInviteKind.Sended);
        DebugTools.Assert(_party.SendedInvites.Contains(invite));
        DebugTools.AssertEqual(_party.LocalParty?.Id, invite.PartyId);
        Invite = invite;

        _party.InviteUpdated += args =>
        {
            if (args != Invite)
                return;

            Refresh();
        };

        CancelButton.OnPressed += _ =>
        {
            _party.DeleteInviteRequest(Invite.Id);
        };

        PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(60, 60, 60) };
        Refresh();
    }

    public void Refresh()
    {
        var receiverName = !string.IsNullOrEmpty(Invite.TargetName) ? Invite.TargetName : "unknown";
        ReceiverLabel.SetMarkup(Loc.GetString("ui-local-party-invite-panel-receiver-label", ("receiver", Invite.TargetName)));

        var status = ISharedPartyInvite.GetPartyInviteStatusName(Invite.Status);
        StatusLabel.SetMarkup(Loc.GetString("ui-local-party-invite-panel-status-label", ("status", status)));
    }
}
